name: "Kube Diagrams"
description: "Generate architecture diagrams from Kubernetes manifests and Helm charts."

inputs:
  type:
    description: "Input type"
    required: true
    default: "kubernetes"
  args:
    description: "Arguments to pass into the tool"
    required: true
    default: ""

runs:
  using: "docker"
  image: "philippemerle/kubediagrams:latest"
  args:
    - ${{ inputs.type == 'helm' && 'kube-diagrams' || 'helm-diagrams' }}
    - ${{ fromJSON(format('["%s"]', join('","', split(' ', inputs.args))) }}

branding:
  icon: "image"
  color: "blue"
